### ISSUE TITLE
ChecklistProjects 

### ISSUE THREAD

**Issue by akoontz11** [pearselab/SymbiotaR2#1]
2 notes on this:

1. Calling `do.call(rbind, Symbiota2Object)` on the R object returned from the `download.file` command (see [this line](https://github.com/pearselab/Symbiota2/blob/488e1f1f57807f25017a7e13529b56b70c5567f2/R/Symbiota2.R#L26))--the result of this is just one huge list, which seems much less informative than the list of lists (the original structure of the `hydra.member` object). Would you still recommend doing this? Perhaps this is me not understanding the larger context in which this command would be used...

2. I created a 2nd command for the 2nd `GET` call listed under ChecklistProjects in the API (instead of wrapping both into 1 command), because both of them take an integer value as an argument, and I wouldn't know how to discriminate whether the user would want to call one command vs. the other (i.e. I don't think I could use `missing`).

**Comment by willpearse** [comment]
1. However you do it, what you want is to return a `data.frame` of some
sort that is useful. So something like `do.call(rbind, SOMETHING)` might
work, but the trick will be figuring out what 'SOMETHING' is. If you are
doing it on the raw output, I think that will be wrong - look at the fourth
slot, which is something that looks like the actual data to me. Does that
help for context? The idea is to give the user something useful, Austin,
and you can get there however you want.

2. Why not have a function something like this:

```{R}
dummy <- function(id, page){
    if(!is.missing(id)){
        do.the.id.stuff()
        return(the.id.stuff)
    }
    if(is.missing(page))
        page <- 1
    do.the.page.stuff()
    return(the.page.stuff)
}
```

...make sense? That way you'd handle both, and we're giving a sensible
default ("just give me everything!") and the user can call things
separately with something like `dummy(id=123456)` or `dummy(page=5,
max.checklists=100)` or something.

**Comment by akoontz11** [comment]
On point 2: if set up this way, the user would _have_ to specify their arguments in the function call, correct? i.e. `id =` or `page =`, as the function could take one or the other, but not both.

**Comment by willpearse** [comment]
Yes, but the API won't let them specify both at the same time anyway. You
could add a check to see if they've specified both and then return an
error, or (in my opinion fine) simply point out in the help file that your
function can only do one thing at a time. Make sense?

**Comment by akoontz11** [comment]
Yeah, seems simple enough. Thanks!

**Comment by akoontz11** [comment]
2 questions on this:

1. I don't think the objects I'm outputting are structured properly--I'm calling `sapply(RObjectFromSymbiota, as.data.frame)`. I can't demonstrate it with `ChecklistProjects` (because of this different issue of items in the list being different lengths, which we saw on Monday...I'll get to that later). But check it out [here](https://github.com/pearselab/Symbiota2/blob/dd2f12a9669bc8d41e92dd38a856d84fed19b997/R/Symbiota2.R#L102-L103) in the `Children` fxn. The output from this function doesn't seem right, does it?

2.  You've asked me to incorporate a `max.checklists` argument to these commands, but I'm not sure how it's meant to work. Is it meant to parse down the list of lists generated (the `hydra:member` object) to the size specified, if what's pulled from the server is initially larger than that size?

**Comment by willpearse** [comment]
Show me what the structure is (copy-paste into this thread)

>

**Comment by akoontz11** [comment]
`List of 77
 $ : Factor w/ 1 level "/api/checklist/children/checklistIdChild=5;checklistId=1": 1
 $ : Factor w/ 1 level "Children": 1
 $ : Factor w/ 1 level "/api/checklists/5": 1
 $ : Factor w/ 1 level "/api/users/1": 1
 $ : logi NA
 $ : Factor w/ 1 level "2019-01-12T11:34:09+00:00": 1
 $ : Factor w/ 1 level "/api/checklists/1": 1
 $ : Factor w/ 1 level "/api/checklist/children/checklistIdChild=5;checklistId=4": 1
 $ : Factor w/ 1 level "Children": 1
 $ : Factor w/ 1 level "/api/checklists/5": 1
 $ : Factor w/ 1 level "/api/users/4": 1
 $ : logi NA
 $ : Factor w/ 1 level "2019-01-12T11:34:09+00:00": 1
 $ : Factor w/ 1 level "/api/checklists/4": 1
 $ : Factor w/ 1 level "/api/checklist/children/checklistIdChild=2;checklistId=6": 1
 $ : Factor w/ 1 level "Children": 1
 $ : Factor w/ 1 level "/api/checklists/2": 1
 $ : Factor w/ 1 level "/api/users/4": 1
 $ : logi NA
 $ : Factor w/ 1 level "2019-01-12T11:34:09+00:00": 1
 $ : Factor w/ 1 level "/api/checklists/6": 1
 $ : Factor w/ 1 level "/api/checklist/children/checklistIdChild=2;checklistId=7": 1
 $ : Factor w/ 1 level "Children": 1
 $ : Factor w/ 1 level "/api/checklists/2": 1
 $ : Factor w/ 1 level "/api/users/1": 1
 $ : logi NA
 $ : Factor w/ 1 level "2019-01-12T11:34:09+00:00": 1
 $ : Factor w/ 1 level "/api/checklists/7": 1
 $ : Factor w/ 1 level "/api/checklist/children/checklistIdChild=6;checklistId=8": 1
 $ : Factor w/ 1 level "Children": 1
 $ : Factor w/ 1 level "/api/checklists/6": 1
 $ : Factor w/ 1 level "/api/users/10": 1
 $ : logi NA
 $ : Factor w/ 1 level "2019-01-12T11:34:09+00:00": 1
 $ : Factor w/ 1 level "/api/checklists/8": 1
 $ : Factor w/ 1 level "/api/checklist/children/checklistIdChild=7;checklistId=8": 1
 $ : Factor w/ 1 level "Children": 1
 $ : Factor w/ 1 level "/api/checklists/7": 1
 $ : Factor w/ 1 level "/api/users/10": 1
 $ : logi NA
 $ : Factor w/ 1 level "2019-01-12T11:34:09+00:00": 1
 $ : Factor w/ 1 level "/api/checklists/8": 1
 $ : Factor w/ 1 level "/api/checklist/children/checklistIdChild=2;checklistId=9": 1
 $ : Factor w/ 1 level "Children": 1
 $ : Factor w/ 1 level "/api/checklists/2": 1
 $ : Factor w/ 1 level "/api/users/10": 1
 $ : logi NA
 $ : Factor w/ 1 level "2019-01-12T11:34:09+00:00": 1
 $ : Factor w/ 1 level "/api/checklists/9": 1
 $ : Factor w/ 1 level "/api/checklist/children/checklistIdChild=6;checklistId=11": 1
 $ : Factor w/ 1 level "Children": 1
 $ : Factor w/ 1 level "/api/checklists/6": 1
 $ : Factor w/ 1 level "/api/users/8": 1
 $ : logi NA
 $ : Factor w/ 1 level "2019-01-12T11:34:09+00:00": 1
 $ : Factor w/ 1 level "/api/checklists/11": 1
 $ : Factor w/ 1 level "/api/checklist/children/checklistIdChild=6;checklistId=13": 1
 $ : Factor w/ 1 level "Children": 1
 $ : Factor w/ 1 level "/api/checklists/6": 1
 $ : Factor w/ 1 level "/api/users/9": 1
 $ : logi NA
 $ : Factor w/ 1 level "2019-01-12T11:34:09+00:00": 1
 $ : Factor w/ 1 level "/api/checklists/13": 1
 $ : Factor w/ 1 level "/api/checklist/children/checklistIdChild=18;checklistId=19": 1
 $ : Factor w/ 1 level "Children": 1
 $ : Factor w/ 1 level "/api/checklists/18": 1
 $ : Factor w/ 1 level "/api/users/8": 1
 $ : logi NA
 $ : Factor w/ 1 level "2019-01-12T17:13:26+00:00": 1
 $ : Factor w/ 1 level "/api/checklists/19": 1
 $ : Factor w/ 1 level "/api/checklist/children/checklistIdChild=21;checklistId=20": 1
 $ : Factor w/ 1 level "Children": 1
 $ : Factor w/ 1 level "/api/checklists/21": 1
 $ : Factor w/ 1 level "/api/users/1": 1
 $ : logi NA
 $ : Factor w/ 1 level "2019-01-12T17:13:26+00:00": 1
 $ : Factor w/ 1 level "/api/checklists/20": 1
 - attr(*, "dim")= int [1:2] 7 11
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:7] "X.id" "X.type" "checklistIdChild" "modifiedUserId" ...
  ..$ : NULL`

**Comment by willpearse** [comment]
This could be right, to be honest, as I've no idea what `children` refers
to. I would move onto a different function that's a bit more obviously
useful to a biologist (maybe the record grabbing stuff) and come back to
this one.
