### ISSUE TITLE
Conversion to data.frame error

### ISSUE THREAD

**Issue by akoontz11** [pearselab/SymbiotaR2#2]
There are several functions that send me an error when I try to convert them to `data.frame` (using `sapply(RObject, as.data.frame)`. [Here's](https://github.com/pearselab/Symbiota2/blob/4646c2ba27996be1e07053c98b8755106d8f9138/R/Symbiota2.R#L2610) a link to one example, in case it helps. The issue occurs when I'm trying to return a `page` of resources, and the error is "arguments imply differing number of rows: 1, 0". My understanding is that this indicates that the lists being passed into the data.frame are of different lengths, but it's stumping me because from what I'm able to tell, that's not the case with list of lists that I'm providing...

If you have any suggestions of things to try, let me know. I'm still working on the tests (i.e. `test_that`) for the functions that are working/not throwing errors.

**Comment by willpearse** [comment]
You're almost certainly correct about what you think the error is. I would
advise you to very carefully take a look at the *str* of the input data...

**Comment by akoontz11** [comment]
You're right: examining this more closely, I found the (sub)lists that are of varying lengths. Of course, the question now is what I should do about it...my thinking is to instead return a `list` rather than a `data.frame`, the downside being that this makes the returns structurally inconsistent between functions. But I don't see an alternative with `data.frame`, so that's my plan going ahead.

**Comment by willpearse** [comment]
Do that for now.
