### ISSUE TITLE
test_functions.R

### ISSUE THREAD

**Issue by akoontz11** [pearselab/SymbiotaR2#3]
Two notes on the API function tests (code in the `/tests` folder):
1. These function checks are based around the expected outputs of given calls, but those outputs will change depending on the [Symbiota2 database](https://symbiota2.github.io/Symbiota2/setup/populate_database.html) the user is calling. I'm using the outputs from the development database as the comparison to check against (which seems reasonable), but I'm wondering if this is something to worry about? Or at least, if there's a way we can make users more aware of this requirement.

2. The tests as they stand now are a little sparse/repetitive--mostly, I'm just checking the `length()` of what's being outputted, and making sure that it's a `list`. These can become more detailed if needed, but for now I feel they're distinctive enough.

**Comment by willpearse** [comment]
When it comes to tests, honestly you're above 98% of the population simply by having them. I think these are good, though.

We will fix the database problem when we write the code to allow users to connect to other databases; these ones will only run against the development server and so all will be well.

Good job, Austin!!!
