### ISSUE TITLE
vcr: tests failing with download using GET from httr

### ISSUE THREAD

**Issue by akoontz11** [pearselab/SymbiotaR2#8]
[I've updated](https://github.com/pearselab/SymbiotaR2/blob/efd32428cb0a621d92d8b5197a637779a89f907e/R/utils.R#L20) the `.api.scaffold` and `.check.api` functions to use `GET` from `httr` rather than `curl` for the download. Everything seems to be working as expected with the new commands.

However: the tests are now failing when I call `use_cassette` (example [here](https://github.com/pearselab/SymbiotaR2/blob/efd32428cb0a621d92d8b5197a637779a89f907e/tests/testthat/test_Checklist.R#L5)). I've pasted the output below for the `ChecklistProjects_ID` example--the error being received is "cannot open the connection" (even though the functions seem to work and pull data from the API when I run them on my own...).
```
> use_cassette(name="ChecklistProjects_ID", {
+   test_that("ChecklistProjects_ID",{
+     data <- ChecklistProjects(url=url, ID=1)
+     expect_equal(length(data),  19)
+     expect_type(data, "list")
+   })
+ })
CrulAdapter enabled!
HttrAdapter enabled!
 Error: Test failed: 'ChecklistProjects_ID'
* cannot open the connection
1: ChecklistProjects(url = url, ID = 1) at :3
2: .api.scaffold(.check.api.entry("checklist/checklistprojects"), url, ID, page) at :4
3: fromJSON(file = dwn_file) at :15
4: paste(readLines(file, warn = FALSE), collapse = "")
5: readLines(file, warn = FALSE)
6: file(con, "r") 
  11. stop("Test failed: '", test, "'\n", messages, call. = FALSE) 
  10. get_reporter()$end_test(context = get_reporter()$.context, test = test) 
  9. test_code(desc, code, env = parent.frame()) 
  8. test_that("ChecklistProjects_ID", {
         data <- ChecklistProjects(url = url, ID = 1)
         expect_equal(length(data), 19)
         expect_type(data, "list") ... 
  7. eval(x$expr, x$env, emptyenv()) 
  6. eval(x$expr, x$env, emptyenv()) 
  5. FUN(X[[i]], ...) 
  4. lapply(x, lazy_eval, data = data) 
  3. lazyeval::lazy_eval(tmp) 
  2. cassette$call_block(...) 
  1. use_cassette(name = "ChecklistProjects_ID", {
         test_that("ChecklistProjects_ID", {
             data <- ChecklistProjects(url = url, ID = 1)
             expect_equal(length(data), 19) ... 
ejecting cassette: ChecklistProjects_ID
CrulAdapter disabled!
HttrAdapter disabled!
```

**Comment by akoontz11** [comment]
I haven't been able to move past this issue, but I've found that this "cannot open the connection" error in the tests is being generated by the `fromJSON` command after the `httr` `GET` command ([here](https://github.com/pearselab/SymbiotaR2/blob/efd32428cb0a621d92d8b5197a637779a89f907e/R/utils.R#L22)). This error is **not** triggered when I run the commands outside of the test; for the above example, if I just run `data <- ChecklistProjects(url=url, ID=1)`, it works fine. But I can't figure out why running the same command within `test_that` fails--maybe something to do with permissions in accessing the temp file?

**Comment by willpearse** [comment]
You need to make the `Users` functions use the new wrappers; they're failing the tests because they're still using `download.file`.

**Comment by akoontz11** [comment]
I ended up moving `Users` into the `Different.R` script (which is part of the code in [this](https://gist.github.com/akoontz11/5e8b3770d65feffbf470648cb9b570fd) gist) because it doesn't use the `page` argument like the rest of the functions (and so it won't work with the new wrappers).

**Comment by willpearse** [comment]
Great - issue closed! :D
